import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { Suspense } from "react";

import { GeistMono } from "geist/font/mono";

import { Toaster } from "@/components/ui/sonner";

import { ThemeProvider } from "next-themes";

import Navbar from "@/components/navbar";
import QueryClientProviders from "@/providers/react-query";
import ErrorSearchParams from "@/components/error-searchparams";
import { ReactScan } from "@/components/react-scan";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`antialiased ${inter.variable} ${GeistMono.variable}`}
    >
      <ReactScan />
      <QueryClientProviders>
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <body>
            <div className="pt-4 pb-24 md:py-24">
              <Suspense>
                <Navbar />
              </Suspense>
              {children}
              <ErrorSearchParams />
              <Toaster />
            </div>
          </body>
        </ThemeProvider>
        <ReactQueryDevtools />
      </QueryClientProviders>
    </html>
  );
}
